services:
  database:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: process.env.POSTGRES_USER
      POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD
      POSTGRES_DB: process.env.POSTGRES_DATABASE
    ports:
      - "5432:5432"